### ISSUE TITLE
bikeshed update --skip-manifest fails with python 3.9

### ISSUE THREAD

**Issue by plinss** [tabatkins/bikeshed#1813]
Output is:

```
...
Downloading data for spec 204/212...
Success!
Downloading biblio data...
Success!
Downloading Can I Use data...
FATAL ERROR: The Can I Use data wasn't valid JSON for some reason. Try downloading again?
__init__() got an unexpected keyword argument 'encoding'
 ✘  Did not generate, due to fatal errors
```

Works fine with Python 3.7.x and 3.8.x

**Comment by tabatkins** [comment]
Okay, it looks like `encoding` doesn't do anything in Py3 anyway, so I can just remove it; I guess the JSON functions take strings now, not bytes, so it makes sense that it's irrelevant. ^_^

**Comment by jyasskin** [comment]
Fixed by #2321.
